name = "LevelSetAdvection"
uuid = "a87bfabe-56cb-40bc-b3ea-027cb9b3338b"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Gridap = "0.16"
Reexport = "1"
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test"]
